server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/collecttechnology?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikariCP
      minimum-idle: 3
      maximum-pool-size: 4
  redis:
    host: r-uf643648d89084c4pd.redis.rds.aliyuncs.com
    port: 6379
    password: ?6.dLOVEve
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最多阻塞等待时间 -1表示没有限制
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲连接数
        min-idle: 8
        #连接超时时间 毫秒
    timeout: 10000
  resources:
    static-locations: classpath:/static/,classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
